### ISSUE TITLE
Swift 4 errors

### ISSUE THREAD

**Issue by orazz** [onmyway133/Reindeer#1]
![screen shot 2017-07-10 at 12 01 47 pm](https://user-images.githubusercontent.com/8214953/28006174-9eabdeee-6567-11e7-8268-1632324fcf98.png)

**Comment by onmyway133** [comment]
@orazz Hi, I haven't started transitioning to Swift 4 yet. Will take a look at it

**Comment by onmyway133** [comment]
@orazz Hi, sorry for late work. You can now check https://github.com/onmyway133/Reindeer/releases/tag/1.0.0 👍
