### ISSUE TITLE
No such module 'Clibxml2'

### ISSUE THREAD

**Issue by niklasberglund** [onmyway133/Reindeer#2]
Just updated to the 1.0.0 release using Cocoapods. When building I'm getting an error in _Document.swift_:
> No such module 'Clibxml2'

**Comment by onmyway133** [comment]
@niklasberglund Hi, are you building for iOS or macOS?

**Comment by keneseste** [comment]
me too. i'm building for iOS
<img width="313" alt="schermata 2017-11-10 alle 11 11 47" src="https://user-images.githubusercontent.com/17107473/32653385-06ffaa2e-c608-11e7-9a38-44d3dcd15e0b.png">

**Comment by niklasberglund** [comment]
@onmyway133 building for iOS

**Comment by onmyway133** [comment]
@niklasberglund @keneseste Hi, I see. I will check

**Comment by niklasberglund** [comment]
@onmyway133 much appreciated! Let me know if I can help.

**Comment by niklasberglund** [comment]
Could it be because the module maps aren't referenced to in the podspec?

**Comment by mstoebe** [comment]
same problem here :(
any news?

**Comment by onmyway133** [comment]
@niklasberglund @mstoebe Can you try the latest commit on master? I tried fixing with multiple module maps, and with 1 umbrella module map. It works in demo projects, you can see in `Example` folder. However, `pod lib lib` does not pass

**Comment by onmyway133** [comment]
It seems `pod lib lint` has some problem linting the project with module map. `pod spec lint` works. So can you check https://github.com/onmyway133/Reindeers/releases/tag/1.2.0? I also renamed it to `Reindeers` to be able to publish on Cocoapods

**Comment by keneseste** [comment]
Hi, how can i Intall it on Snowflake?  

the instruction are:
simply add the following line to your Podfile:
pod 'Reindeer', git: 'https://github.com/onmyway133/Reindeer'
pod 'Snowflake', git: 'https://github.com/onmyway133/Snowflake'

but now i have come errors and if i try so:
pod 'Reindeers', git: 'https://github.com/onmyway133/Reindeers'
pod 'Snowflake', git: 'https://github.com/onmyway133/Snowflake'

in my pod intall:
<img width="236" alt="schermata 2017-11-13 alle 16 52 34" src="https://user-images.githubusercontent.com/17107473/32734723-1f6d4246-c893-11e7-9a5f-4c847a022522.png">

and in app i have many error
<img width="259" alt="schermata 2017-11-13 alle 16 53 58" src="https://user-images.githubusercontent.com/17107473/32734795-4ffbc0ae-c893-11e7-83ee-78effa3d1d02.png">

Thanks

**Comment by onmyway133** [comment]
@keneseste are you using Swift 4? I will fix Snowflake to reference the new `Reindeers`

**Comment by keneseste** [comment]
@onmyway133 Yes I'm using swift 4. Thank you so much.

**Comment by niklasberglund** [comment]
Good stuff! I'm also using Snowflake. The project it's used in is still on Swift 3. Will let you know how it goes once Snowflake has been updated to use Reindeers.

**Comment by onmyway133** [comment]
@keneseste @niklasberglund I will close this for now. Feel free to reopen the issue on Snowflake. I will fix it as soon as possible

**Comment by onmyway133** [comment]
@niklasberglund @keneseste Hi, you can now check https://github.com/onmyway133/Snowflake/releases/tag/2.0.0

**Comment by niklasberglund** [comment]
@onmyway133 thank you, it's working well 👍
